# Configuration file for in memory database
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: sa
    driver-class-name: org.h2.Driver